; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.0 on Sun Dec 27 2020 17:30:28 GMT+0100 (Mitteleuropäische Normalzeit)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation
G30 P0 X20 Y190 Z-99999 ; probe near a leadscrew
G30 P1 X180 Y190 Z-99999 ; probe near a leadscrew