; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.0 on Sun Dec 27 2020 17:30:28 GMT+0100 (Mitteleuropäische Normalzeit)
M280 P0 S10 ; deploy BLTouch

