; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.0 on Sun Dec 27 2020 17:30:28 GMT+0100 (Mitteleuropäische Normalzeit)
M280 P0 S90 ; retract BLTouch

