; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.0 on Sun Dec 27 2020 17:30:28 GMT+0100 (Mitteleuropäische Normalzeit)
; Wait for set temperatures to be reached
M116 P1

